# Generated by Django 5.1 on 2024-09-01 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='data_hora_partida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jogador',
            name='tentativas',
            field=models.IntegerField(default=0),
        ),
    ]
