# Generated by Django 5.1 on 2024-09-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0003_jogador_tempo_total_alter_jogador_apelido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='tempo_total',
        ),
    ]
